// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketing.Infrastructure.Data;

#nullable disable

namespace Ticketing.Infrastructure.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    [Migration("20260501154928_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ticketing.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("EVENT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Conferencia de Inteligencia Artificial 2026",
                            Status = "Active",
                            Venue = "Auditorio Tecnológico - Sala Principal"
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RESERVATION");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("SEAT");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            RowIdentifier = "F1",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000002"),
                            RowIdentifier = "F1",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000003"),
                            RowIdentifier = "F1",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000004"),
                            RowIdentifier = "F1",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000005"),
                            RowIdentifier = "F1",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000006"),
                            RowIdentifier = "F1",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000007"),
                            RowIdentifier = "F1",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000008"),
                            RowIdentifier = "F1",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000009"),
                            RowIdentifier = "F1",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000010"),
                            RowIdentifier = "F1",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000011"),
                            RowIdentifier = "F2",
                            SeatNumber = 11,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000012"),
                            RowIdentifier = "F2",
                            SeatNumber = 12,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000013"),
                            RowIdentifier = "F2",
                            SeatNumber = 13,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000014"),
                            RowIdentifier = "F2",
                            SeatNumber = 14,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000015"),
                            RowIdentifier = "F2",
                            SeatNumber = 15,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000016"),
                            RowIdentifier = "F2",
                            SeatNumber = 16,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000017"),
                            RowIdentifier = "F2",
                            SeatNumber = 17,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000018"),
                            RowIdentifier = "F2",
                            SeatNumber = 18,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000019"),
                            RowIdentifier = "F2",
                            SeatNumber = 19,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000020"),
                            RowIdentifier = "F2",
                            SeatNumber = 20,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000021"),
                            RowIdentifier = "F3",
                            SeatNumber = 21,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000022"),
                            RowIdentifier = "F3",
                            SeatNumber = 22,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000023"),
                            RowIdentifier = "F3",
                            SeatNumber = 23,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000024"),
                            RowIdentifier = "F3",
                            SeatNumber = 24,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000025"),
                            RowIdentifier = "F3",
                            SeatNumber = 25,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000026"),
                            RowIdentifier = "F3",
                            SeatNumber = 26,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000027"),
                            RowIdentifier = "F3",
                            SeatNumber = 27,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000028"),
                            RowIdentifier = "F3",
                            SeatNumber = 28,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000029"),
                            RowIdentifier = "F3",
                            SeatNumber = 29,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000030"),
                            RowIdentifier = "F3",
                            SeatNumber = 30,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000031"),
                            RowIdentifier = "F4",
                            SeatNumber = 31,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000032"),
                            RowIdentifier = "F4",
                            SeatNumber = 32,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000033"),
                            RowIdentifier = "F4",
                            SeatNumber = 33,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000034"),
                            RowIdentifier = "F4",
                            SeatNumber = 34,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000035"),
                            RowIdentifier = "F4",
                            SeatNumber = 35,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000036"),
                            RowIdentifier = "F4",
                            SeatNumber = 36,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000037"),
                            RowIdentifier = "F4",
                            SeatNumber = 37,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000038"),
                            RowIdentifier = "F4",
                            SeatNumber = 38,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000039"),
                            RowIdentifier = "F4",
                            SeatNumber = 39,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000040"),
                            RowIdentifier = "F4",
                            SeatNumber = 40,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000041"),
                            RowIdentifier = "F5",
                            SeatNumber = 41,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000042"),
                            RowIdentifier = "F5",
                            SeatNumber = 42,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000043"),
                            RowIdentifier = "F5",
                            SeatNumber = 43,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000044"),
                            RowIdentifier = "F5",
                            SeatNumber = 44,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000045"),
                            RowIdentifier = "F5",
                            SeatNumber = 45,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000046"),
                            RowIdentifier = "F5",
                            SeatNumber = 46,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000047"),
                            RowIdentifier = "F5",
                            SeatNumber = 47,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000048"),
                            RowIdentifier = "F5",
                            SeatNumber = 48,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000049"),
                            RowIdentifier = "F5",
                            SeatNumber = 49,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000050"),
                            RowIdentifier = "F5",
                            SeatNumber = 50,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000051"),
                            RowIdentifier = "F1",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000052"),
                            RowIdentifier = "F1",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000053"),
                            RowIdentifier = "F1",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000054"),
                            RowIdentifier = "F1",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000055"),
                            RowIdentifier = "F1",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000056"),
                            RowIdentifier = "F1",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000057"),
                            RowIdentifier = "F1",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000058"),
                            RowIdentifier = "F1",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000059"),
                            RowIdentifier = "F1",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000060"),
                            RowIdentifier = "F1",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000061"),
                            RowIdentifier = "F2",
                            SeatNumber = 11,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000062"),
                            RowIdentifier = "F2",
                            SeatNumber = 12,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000063"),
                            RowIdentifier = "F2",
                            SeatNumber = 13,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000064"),
                            RowIdentifier = "F2",
                            SeatNumber = 14,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000065"),
                            RowIdentifier = "F2",
                            SeatNumber = 15,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000066"),
                            RowIdentifier = "F2",
                            SeatNumber = 16,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000067"),
                            RowIdentifier = "F2",
                            SeatNumber = 17,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000068"),
                            RowIdentifier = "F2",
                            SeatNumber = 18,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000069"),
                            RowIdentifier = "F2",
                            SeatNumber = 19,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000070"),
                            RowIdentifier = "F2",
                            SeatNumber = 20,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000071"),
                            RowIdentifier = "F3",
                            SeatNumber = 21,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000072"),
                            RowIdentifier = "F3",
                            SeatNumber = 22,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000073"),
                            RowIdentifier = "F3",
                            SeatNumber = 23,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000074"),
                            RowIdentifier = "F3",
                            SeatNumber = 24,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000075"),
                            RowIdentifier = "F3",
                            SeatNumber = 25,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000076"),
                            RowIdentifier = "F3",
                            SeatNumber = 26,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000077"),
                            RowIdentifier = "F3",
                            SeatNumber = 27,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000078"),
                            RowIdentifier = "F3",
                            SeatNumber = 28,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000079"),
                            RowIdentifier = "F3",
                            SeatNumber = 29,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000080"),
                            RowIdentifier = "F3",
                            SeatNumber = 30,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000081"),
                            RowIdentifier = "F4",
                            SeatNumber = 31,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000082"),
                            RowIdentifier = "F4",
                            SeatNumber = 32,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000083"),
                            RowIdentifier = "F4",
                            SeatNumber = 33,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000084"),
                            RowIdentifier = "F4",
                            SeatNumber = 34,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000085"),
                            RowIdentifier = "F4",
                            SeatNumber = 35,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000086"),
                            RowIdentifier = "F4",
                            SeatNumber = 36,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000087"),
                            RowIdentifier = "F4",
                            SeatNumber = 37,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000088"),
                            RowIdentifier = "F4",
                            SeatNumber = 38,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000089"),
                            RowIdentifier = "F4",
                            SeatNumber = 39,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000090"),
                            RowIdentifier = "F4",
                            SeatNumber = 40,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000091"),
                            RowIdentifier = "F5",
                            SeatNumber = 41,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000092"),
                            RowIdentifier = "F5",
                            SeatNumber = 42,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000093"),
                            RowIdentifier = "F5",
                            SeatNumber = 43,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000094"),
                            RowIdentifier = "F5",
                            SeatNumber = 44,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000095"),
                            RowIdentifier = "F5",
                            SeatNumber = 45,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000096"),
                            RowIdentifier = "F5",
                            SeatNumber = 46,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000097"),
                            RowIdentifier = "F5",
                            SeatNumber = 47,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000098"),
                            RowIdentifier = "F5",
                            SeatNumber = 48,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000099"),
                            RowIdentifier = "F5",
                            SeatNumber = 49,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000100"),
                            RowIdentifier = "F5",
                            SeatNumber = 50,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("SECTOR");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Campo General",
                            Price = 95000m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Platea ",
                            Price = 120000m
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("USER");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Ticketing.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Ticketing.Domain.Entities.Seat", "Seat")
                        .WithOne("Reservation")
                        .HasForeignKey("Ticketing.Domain.Entities.Reservation", "SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketing.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Seat", b =>
                {
                    b.HasOne("Ticketing.Domain.Entities.Sector", "Sector")
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Sector", b =>
                {
                    b.HasOne("Ticketing.Domain.Entities.Event", "Event")
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Event", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Seat", b =>
                {
                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
